name: gaussian_mixing
dependencies:
  - python
  - cartopy
  - geopy
  - numpy
  - scipy
  - ipython
  - jupyter
  #- cmcrameri
  - scikit-image
  - matplotlib
  - pyproj
  #- windrose
  - pandas
  - ipympl
